Created a service and move the main functionality (requests sending and results processing) into it.
Flame787898/Drupal-News pull request #51
Opened 2023-01-12 13:18 UTC by Flame787898

https://redmine.devbranch.work/issues/5840

2023-01-15 16:58 UTC, Y0r commented on web/modules/custom/exchange_rates/exchange_rates.module
> + * Hook theme.
bad

2023-01-15 16:58 UTC, Y0r commented on web/modules/custom/exchange_rates/exchange_rates.services.yml
> +    arguments: ['@http_client','@config.factory']
space between arguments

2023-01-15 16:58 UTC, Y0r commented on web/modules/custom/exchange_rates/src/ExchangeAPIConnector.php
> +   */
?

2023-01-15 16:59 UTC, Y0r commented on web/modules/custom/exchange_rates/src/ExchangeAPIConnector.php
> +   */
?

2023-01-15 17:00 UTC, Y0r requested changes
Solve problems first

2023-01-24 16:10 UTC, aidua commented on web/modules/custom/exchange_rates/src/Plugin/Block/ExchangeRatesBlock.php
> +   * @param array $configuration
fix coding standards here and below.

2023-01-26 15:44 UTC, merged